language: node_js
node_js:
    - "4.2"
deploy:
  provider: heroku
  api_key:
    secure: uCL7C6HWsOZZRtX2oWVQkRZeCYz6uhA4UQ7KyIMtv/AT6OCZoIiAQ6bL0pWMRzbAX9j1Z48MT8XOWt3Zw8MlI2vm2nazg8vcfrydFLLO/OrDjlOS+Lid5OvG1iEuQ5IwCbTU5tUwjius+wLyJLx5oKRg6VzLroQnNxw/Cg2MCAv4LHIAcDUWvTZt98A2rqq7jEpw3zxGXgvB9ciztd6x9b5sMZV+UNZVQeY6749Lqiu9Qvq774NR5y+uojVS7tGAvz5zq/iuJ+Nu58U8BHxF5wRdDEUXYt0FntrHC5hNyYxNXfrVbBF5f1BbM5klnDHQRDWXDIciwqQQtr/sT3VDIlviwedeo+EtJNQ1slnDCxa54xIbsEPlD8+Cmvl+h0F5PKQVm/9jTvg3W3PeXgBw3cOHvhh/2t52Qa/rEEXhE9kgeEnSyvfA4AV96uxsNGq1L5X7X7gW6W4FOO+sW5PNBIdcuqENYR+Bx+514x4jxf3yxfhPdIFfrt9OMxlTdKqpFq64sfDXZf85ObIDLOMQkpeoEQIoqa8KpVVe3PMEHGrDjhtAmYSyfDUjJAOJoK2mNuFvjb1Lsc1q2bue5JHtSmmD0xzNK0aHmdcpDcSxXMgjKH8LI1VS5q/Leo9k6XPgZD+asvJQQ4/1AV9FZ92VHbdzObrQufv7rVbczKAfLjQ=
  app: evening-island-89630
  on:
    repo: geektoni/heroku_test
